### ISSUE TITLE
profile faces and different face detector

### ISSUE THREAD

**Issue by nyck33** [wondonghyeon/face-classification#6]
How robust is it on profile faces?

If I use a better face detector will I get better results?  

Some of the demo images of crowds have many faces with no bounding box so I'm wondering.

**Comment by wondonghyeon** [comment]
I am not sure how the model will perform on profile faces. However, I think the model performs better on front-facing faces than side faces. The images where the model is trained on are mostly front-facing faces.

What do you mean by "better results"? I don't think race/gender classification performance will depend on the face detector because you will still use the feature extractor.

**Comment by nyck33** [comment]
Thanks for the reply.  I will consider transfer learning on profile faces.
By better I meant:   more faces detected -> more faces to classify race and gender -> cumulatively more classifications per image.
